# Generated by Django 4.2.4 on 2023-08-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polish_translation', models.CharField(max_length=80)),
                ('english_translation', models.CharField(max_length=80)),
                ('remaining_repetitions', models.IntegerField(default=8)),
            ],
        ),
    ]
