# Generated by Django 4.2.4 on 2023-09-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict_app', '0002_word_english_pronunciation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='english_translation',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
