# Generated by Django 4.2.4 on 2023-09-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict_app', '0004_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
